# Generated by Django 3.2.9 on 2022-02-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id_data_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'smupapp_datatype',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('surname', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.authuser')),
            ],
            options={
                'db_table': 'smupapp_employee',
            },
        ),
        migrations.CreateModel(
            name='Employeetype',
            fields=[
                ('id_employeetype', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'smupapp_employeetype',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id_process', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('tip', models.TextField(blank=True, null=True)),
                ('id_number', models.IntegerField()),
                ('order', models.IntegerField(default=-1)),
                ('number', models.CharField(default='', max_length=256)),
                ('id_mainprocess', models.ForeignKey(blank=True, db_column='id_mainProcess', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.process')),
            ],
            options={
                'db_table': 'smupapp_process',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id_rule', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('max_value', models.FloatField(blank=True, default=0, null=True)),
                ('time_from', models.DateField()),
                ('time_to', models.DateField()),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.datatype')),
            ],
            options={
                'db_table': 'smupapp_rule',
            },
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id_time_range', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'smupapp_timerange',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id_unit', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'smupapp_unit',
            },
        ),
        migrations.CreateModel(
            name='RuleHasProcess',
            fields=[
                ('id_rule_has_process', models.BigAutoField(primary_key=True, serialize=False)),
                ('process_id_process', models.ForeignKey(db_column='process_id_process', on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.process')),
                ('rule_id_rule', models.ForeignKey(db_column='rule_id_rule', on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.rule')),
            ],
            options={
                'db_table': 'smupapp_rulehasprocess',
            },
        ),
        migrations.CreateModel(
            name='RuleHasEmployee',
            fields=[
                ('id_rule_has_employee', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_id_employee', models.ForeignKey(db_column='employee_id_employee', on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.employee')),
                ('rule_id_rule', models.ForeignKey(db_column='rule_id_rule', on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.rule')),
            ],
            options={
                'db_table': 'smupapp_rulehasemployee',
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='time_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.timerange'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_employeetype',
            field=models.ForeignKey(db_column='id_employeetype', on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.employeetype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_unit',
            field=models.ForeignKey(db_column='id_unit', on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.unit'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id_activity', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('time_add', models.DateTimeField(blank=True, null=True)),
                ('time_from', models.DateField(blank=True, null=True)),
                ('time_to', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_id_employee', models.ForeignKey(db_column='employee_id_employee', on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.employee')),
                ('rule_has_process_id_rule_has_process', models.ForeignKey(db_column='rule_has_process_id_rule_has_process', on_delete=django.db.models.deletion.DO_NOTHING, to='smupapp.rulehasprocess')),
            ],
            options={
                'db_table': 'smupapp_activity',
            },
        ),
    ]
