# Generated by Django 3.2.9 on 2022-01-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smupapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
