# Generated by Django 4.0.3 on 2022-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigr1ions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_to',
            field=models.DateField(blank=True, max_length=45, null=True),
        ),
    ]
