# Generated by Django 3.2.9 on 2022-01-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='employeetype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rulehasemployee',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rulehasprocess',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='timerange',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'managed': False},
        ),
    ]
