# Generated by Django 3.2.9 on 2022-01-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smupapp', '0002_auto_20220121_1547'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='datatype',
            table='dataType',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='employeetype',
            table='employeetype',
        ),
        migrations.AlterModelTable(
            name='process',
            table='process',
        ),
        migrations.AlterModelTable(
            name='rule',
            table='rule',
        ),
        migrations.AlterModelTable(
            name='rulehasemployee',
            table='ruleHasEmployee',
        ),
        migrations.AlterModelTable(
            name='rulehasprocess',
            table='ruleHasProcess',
        ),
        migrations.AlterModelTable(
            name='timerange',
            table='timeRange',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='unit',
        ),
    ]
