# Generated by Django 3.2.9 on 2022-01-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smupapp', '0003_process_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='number',
            field=models.CharField(default='', max_length=256),
        ),
    ]
