# Generated by Django 3.2.9 on 2022-02-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smupapp', '0005_alter_rule_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='max',
            field=models.FloatField(default=None),
        ),
    ]
