# Generated by Django 3.2.9 on 2021-11-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('idactivity', models.AutoField(db_column='idActivity', primary_key=True, serialize=False)),
                ('timeconsuming', models.DateTimeField(db_column='timeConsuming')),
                ('timeadd', models.DateTimeField(db_column='timeAdd')),
                ('timefrom', models.DateTimeField(blank=True, db_column='timeFrom', null=True)),
                ('timeto', models.CharField(blank=True, db_column='timeTo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idemployee', models.AutoField(db_column='idEmployee', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('surname', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeetype',
            fields=[
                ('idemployee_type', models.AutoField(db_column='idEmployee Type', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'employeetype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('idprocess', models.AutoField(db_column='idProcess', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('tip', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idrole', models.AutoField(db_column='idRole', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('idunit', models.AutoField(db_column='idUnit', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'userdata',
                'managed': False,
            },
        ),
    ]
