# Generated by Django 3.2.9 on 2021-11-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleHasProcess',
            fields=[
                ('rule_idrule', models.OneToOneField(db_column='rule_idRule', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.rule')),
            ],
            options={
                'db_table': 'rule_has_process',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ActivityHasRule',
        ),
    ]
