# Generated by Django 3.2.9 on 2021-11-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211121_1156'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='process',
            table='process',
        ),
    ]
