# Generated by Django 3.2.9 on 2021-11-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_process_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('ideffect', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('timeadd', models.DateTimeField(db_column='timeAdd')),
                ('timefrom', models.DateField(db_column='timeFrom')),
                ('timeto', models.DateField(db_column='timeTo')),
            ],
            options={
                'db_table': 'effect',
                'managed': False,
            },
        ),
    ]
