# Generated by Django 3.2.9 on 2021-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('idtime_range', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'time_range',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
    ]
