# Generated by Django 3.2.9 on 2021-11-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211127_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('iddata_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'data_type',
                'managed': False,
            },
        ),
    ]
