# Generated by Django 3.2.9 on 2022-01-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_datatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleHasEmployee',
            fields=[
                ('rule_idrule', models.OneToOneField(db_column='rule_idRule', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.rule')),
            ],
            options={
                'db_table': 'rule_has_employee',
                'managed': False,
            },
        ),
    ]
