#
#  pages
#
RENDER_HOME_URL = 'main/home.html'
RENDER_IMPORT_EXPORT_URL = 'importexport/importexport.html'
RENDER_ACTIVITY_URL = 'activity/activity.html'
RENDER_ACTIVITIES_URL = 'activity/activities.html'
RENDER_PROFIL_URL = 'auth/profil.html'
RENDER_LOGIN_URL = 'auth/login.html'
RENDER_UNITS_URL = 'unit/units.html'
RENDER_UNIT_URL = 'unit/unit.html'
RENDER_RULE_URL = 'rule/rule.html'
RENDER_VIEWRULE_URL = 'rule/viewrule.html'
RENDER_RULES_URL = 'rule/rules.html'
RENDER_USER_URL = 'user/user.html'
RENDER_USERS_URL = 'user/users.html'
#
REDIRECT_ACTIVITIES_URL = 'activities'
REDIRECT_HOME_URL = 'home'
REDIRECT_IMPORT_EXPORT_URL = 'importExport'
REDIRECT_UNITS_URL = 'units'
REDIRECT_USERS_URL = 'users'
REDIRECT_USER_URL = 'user'
REDIRECT_RULES_URL = 'rules'
REDIRECT_RULE_URL = 'rule'
